package Feb17;

import java.sql.*;
import javax.swing.*;// lib swing from label to jtextfield, etc 
import java.time.LocalDateTime;// lib time and date
import java.time.format.DateTimeFormatter; // lib time and date

/**
 *
 * @author Ita Puspita
 */
public class input_PIN extends javax.swing.JFrame {

    Status_PIN status = new Status_PIN();
    mySQLConn mysql = new mySQLConn();
    byte block = 0;

    /**
     * Creates new form input_PIN
     */
    public input_PIN() {
        initComponents();
        //setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);//syntax resize sesuai monitor
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelDate1 = new javax.swing.JLabel();
        LabelTime = new javax.swing.JLabel();
        PanelSignal = new javax.swing.JPanel();
        LabelInputPIN = new javax.swing.JLabel();
        Label6Digits = new javax.swing.JLabel();
        TextFieldPIN = new javax.swing.JTextField();
        LabelA1 = new javax.swing.JLabel();
        LabelA2 = new javax.swing.JLabel();
        LabelA3 = new javax.swing.JLabel();
        LabelA4 = new javax.swing.JLabel();
        LabelA5 = new javax.swing.JLabel();
        LabelA6 = new javax.swing.JLabel();
        LabelA8 = new javax.swing.JLabel();
        LabelA9 = new javax.swing.JLabel();
        LabelABintang = new javax.swing.JLabel();
        LabelA0 = new javax.swing.JLabel();
        LabelA7 = new javax.swing.JLabel();
        LabelAPagar = new javax.swing.JLabel();
        LabelBatal = new javax.swing.JLabel();
        LabelNext = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        LabelDate1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        LabelDate1.setText("17-Feb-2017");

        LabelTime.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        LabelTime.setText("21:13");

        PanelSignal.setBackground(new java.awt.Color(51, 153, 0));

        javax.swing.GroupLayout PanelSignalLayout = new javax.swing.GroupLayout(PanelSignal);
        PanelSignal.setLayout(PanelSignalLayout);
        PanelSignalLayout.setHorizontalGroup(
            PanelSignalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        PanelSignalLayout.setVerticalGroup(
            PanelSignalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        LabelInputPIN.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        LabelInputPIN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelInputPIN.setText("Masukkan PIN ");

        Label6Digits.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        Label6Digits.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label6Digits.setText("6 - Angka");
        Label6Digits.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        TextFieldPIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldPINActionPerformed(evt);
            }
        });
        TextFieldPIN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldPINKeyTyped(evt);
            }
        });

        LabelA1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        LabelA1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelA1.setText("1");
        LabelA1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelA1MouseClicked(evt);
            }
        });

        LabelA2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        LabelA2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelA2.setText("2");
        LabelA2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelA2MouseClicked(evt);
            }
        });

        LabelA3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        LabelA3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelA3.setText("3");
        LabelA3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelA3MouseClicked(evt);
            }
        });

        LabelA4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        LabelA4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelA4.setText("4");
        LabelA4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelA4MouseClicked(evt);
            }
        });

        LabelA5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        LabelA5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelA5.setText("5");
        LabelA5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelA5MouseClicked(evt);
            }
        });

        LabelA6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        LabelA6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelA6.setText("6");
        LabelA6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelA6MouseClicked(evt);
            }
        });

        LabelA8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        LabelA8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelA8.setText("8");
        LabelA8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelA8MouseClicked(evt);
            }
        });

        LabelA9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        LabelA9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelA9.setText("9");
        LabelA9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelA9MouseClicked(evt);
            }
        });

        LabelABintang.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        LabelABintang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelABintang.setText("*");
        LabelABintang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelABintangMouseClicked(evt);
            }
        });

        LabelA0.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        LabelA0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelA0.setText("0");
        LabelA0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelA0MouseClicked(evt);
            }
        });

        LabelA7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        LabelA7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelA7.setText("7");
        LabelA7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelA7MouseClicked(evt);
            }
        });

        LabelAPagar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        LabelAPagar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelAPagar.setText("#");
        LabelAPagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelAPagarMouseClicked(evt);
            }
        });

        LabelBatal.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        LabelBatal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelBatal.setText("Batal");
        LabelBatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelBatalMouseClicked(evt);
            }
        });

        LabelNext.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        LabelNext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelNext.setText("Lanjutkan");
        LabelNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelNextMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelDate1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelTime)
                        .addGap(91, 91, 91)
                        .addComponent(PanelSignal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelInputPIN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldPIN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label6Digits, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelA8)
                                    .addComponent(LabelA0))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelAPagar)
                                    .addComponent(LabelA9)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(LabelBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelNext, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelA1)
                            .addComponent(LabelA4)
                            .addComponent(LabelA7)
                            .addComponent(LabelABintang))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelA2)
                            .addComponent(LabelA5))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelA6)
                            .addComponent(LabelA3))
                        .addGap(64, 64, 64)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelTime)
                        .addComponent(LabelDate1))
                    .addComponent(PanelSignal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelA9)
                        .addGap(26, 26, 26)
                        .addComponent(LabelAPagar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelInputPIN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Label6Digits, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldPIN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelA1)
                            .addComponent(LabelA2)
                            .addComponent(LabelA3))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelA4)
                            .addComponent(LabelA5)
                            .addComponent(LabelA6))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelA7)
                                .addGap(26, 26, 26)
                                .addComponent(LabelABintang))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelA8)
                                .addGap(26, 26, 26)
                                .addComponent(LabelA0)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelBatal)
                    .addComponent(LabelNext))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldPINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldPINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldPINActionPerformed

    private void LabelA1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelA1MouseClicked
        if (TextFieldPIN.getText().length() <= 5) {// sytax untuk membatasi char 
            TextFieldPIN.setText(TextFieldPIN.getText().intern() + "1");//syntax label to textfield
        }
    }//GEN-LAST:event_LabelA1MouseClicked

    private void LabelA2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelA2MouseClicked
        if (TextFieldPIN.getText().length() <= 5) {// sytax untuk membatasi char 
            TextFieldPIN.setText(TextFieldPIN.getText().intern() + "2");//syntax label to textfield
        }
    }//GEN-LAST:event_LabelA2MouseClicked

    private void LabelA3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelA3MouseClicked
        if (TextFieldPIN.getText().length() <= 5) {// sytax untuk membatasi char 
            TextFieldPIN.setText(TextFieldPIN.getText().intern() + "3");//syntax label to textfield
        }
    }//GEN-LAST:event_LabelA3MouseClicked

    private void LabelA4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelA4MouseClicked
        if (TextFieldPIN.getText().length() <= 5) {// sytax untuk membatasi char 
            TextFieldPIN.setText(TextFieldPIN.getText().intern() + "4");//syntax label to textfield
        }
    }//GEN-LAST:event_LabelA4MouseClicked

    private void LabelA5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelA5MouseClicked
        if (TextFieldPIN.getText().length() <= 5) {// sytax untuk membatasi char 
            TextFieldPIN.setText(TextFieldPIN.getText().intern() + "5");//syntax label to textfield
        }//syntax label to textfield
    }//GEN-LAST:event_LabelA5MouseClicked

    private void LabelA6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelA6MouseClicked
        if (TextFieldPIN.getText().length() <= 5) {// sytax untuk membatasi char 
            TextFieldPIN.setText(TextFieldPIN.getText().intern() + "6");//syntax label to textfield
        }
    }//GEN-LAST:event_LabelA6MouseClicked

    private void LabelA7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelA7MouseClicked
        if (TextFieldPIN.getText().length() <= 5) {// sytax untuk membatasi char 
            TextFieldPIN.setText(TextFieldPIN.getText().intern() + "7");//syntax label to textfield
        }//syntax label to textfield
    }//GEN-LAST:event_LabelA7MouseClicked

    private void LabelA8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelA8MouseClicked
        if (TextFieldPIN.getText().length() <= 5) {// sytax untuk membatasi char 
            TextFieldPIN.setText(TextFieldPIN.getText().intern() + "8");//syntax label to textfield
        }
    }//GEN-LAST:event_LabelA8MouseClicked

    private void LabelA9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelA9MouseClicked
        if (TextFieldPIN.getText().length() <= 5) {// sytax untuk membatasi char 
            TextFieldPIN.setText(TextFieldPIN.getText().intern() + "9");//syntax label to textfield
        }
    }//GEN-LAST:event_LabelA9MouseClicked

    private void LabelABintangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelABintangMouseClicked
        if (TextFieldPIN.getText().length() <= 5) {// sytax untuk membatasi char 
            TextFieldPIN.setText(TextFieldPIN.getText().intern() + "*");//syntax label to textfield
        }
    }//GEN-LAST:event_LabelABintangMouseClicked

    private void LabelA0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelA0MouseClicked
        if (TextFieldPIN.getText().length() <= 5) {// sytax untuk membatasi char 
            TextFieldPIN.setText(TextFieldPIN.getText().intern() + "0");//syntax label to textfield
        }
    }//GEN-LAST:event_LabelA0MouseClicked

    private void LabelAPagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelAPagarMouseClicked
        if (TextFieldPIN.getText().length() <= 5) {// sytax untuk membatasi char 
            TextFieldPIN.setText(TextFieldPIN.getText().intern() + "#");//syntax label to textfield
        }
    }//GEN-LAST:event_LabelAPagarMouseClicked

    private void LabelNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelNextMouseClicked
        if (cekPIN(TextFieldPIN.getText().intern()).equals("true")) {
            if (status.getKonfirmasi() != "True") {
                if (TextFieldPIN.getText().length() == 6) {//syntax harus terisi 6 digits 
                    input_nominal nominal = new input_nominal(); // change page
                    nominal.setVisible(true); // change page
                    this.setVisible(false); // code close page
                } else {
                    JOptionPane.showMessageDialog(null, "Masukan PIN 6 Digit");//PopUp
                    TextFieldPIN.setText("");
                }
            } else{
                if (TextFieldPIN.getText().length() == 6) {//syntax harus terisi 6 digits 
                    successed_transaction transaksi = new successed_transaction(); // change page
                    transaksi.setVisible(true); // change page
                    this.setVisible(false); // code close page
                } else {
                    JOptionPane.showMessageDialog(null, "Masukan PIN 6 Digit");//PopUp
                    TextFieldPIN.setText("");

                }
            }
        } else if (cekPIN(TextFieldPIN.getText().intern()).equals("false")) {
            JOptionPane.showMessageDialog(null, "PIN Salah");//PopUp
            TextFieldPIN.setText("");
            block++;

        }
        if (block == 3) {
            JOptionPane.showMessageDialog(null, "Kartu Anda Diblokir");
            try {
                block();

            } catch (Exception e) {
            }
        }
        if (cekPIN(TextFieldPIN.getText().intern()).equals("block")) {
            JOptionPane.showMessageDialog(null, "Kartu Anda Diblokir");
            lock_screen lock = new lock_screen();
            lock.setVisible(true);
            this.setVisible(false);
        }

    }//GEN-LAST:event_LabelNextMouseClicked

    private void TextFieldPINKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldPINKeyTyped

    }//GEN-LAST:event_TextFieldPINKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        java.time.LocalDateTime now = LocalDateTime.now();// syntax time and to label 
        DateTimeFormatter tanggal = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        DateTimeFormatter jam = DateTimeFormatter.ofPattern("H:mm");
        LabelDate1.setText(tanggal.format(now));
        LabelTime.setText(jam.format(now));// end time and date
    }//GEN-LAST:event_formWindowOpened

    private void LabelBatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelBatalMouseClicked
        lock_screen lock = new lock_screen();
        lock.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LabelBatalMouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(input_PIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(input_PIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(input_PIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(input_PIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new input_PIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label6Digits;
    private javax.swing.JLabel LabelA0;
    private javax.swing.JLabel LabelA1;
    private javax.swing.JLabel LabelA2;
    private javax.swing.JLabel LabelA3;
    private javax.swing.JLabel LabelA4;
    private javax.swing.JLabel LabelA5;
    private javax.swing.JLabel LabelA6;
    private javax.swing.JLabel LabelA7;
    private javax.swing.JLabel LabelA8;
    private javax.swing.JLabel LabelA9;
    private javax.swing.JLabel LabelABintang;
    private javax.swing.JLabel LabelAPagar;
    private javax.swing.JLabel LabelBatal;
    private javax.swing.JLabel LabelDate1;
    private javax.swing.JLabel LabelInputPIN;
    private javax.swing.JLabel LabelNext;
    private javax.swing.JLabel LabelTime;
    private javax.swing.JPanel PanelSignal;
    private javax.swing.JTextField TextFieldPIN;
    // End of variables declaration//GEN-END:variables
private String cekPIN(String PIN) {
        String status = "false";
        if (mysql.getConnection()) {
            String getQueryMySQL = "SELECT * FROM tb_edc WHERE id_pin = '" + PIN + "'";
            try {
                Statement smt = mysql.conn.createStatement();
                ResultSet rs = smt.executeQuery(getQueryMySQL);
                if (rs.next()) {
                    status = "true";
                    if (rs.getString("status_id").equals("1")) {
                        status = "block";
                    }
                }
            } catch (Exception e) {
                System.out.println("Error");
            }
        }
        return status;
    }

    private void block() throws Exception {
        if (mysql.getConnection()) {
            String updateBlock = "UPDATE tb_edc SET status_id = '1' WHERE id = '1'";
            Statement stmt = mysql.conn.createStatement();
            stmt.executeUpdate(updateBlock);

        }
    }
}
